### ISSUE TITLE
Error vncreplay

### ISSUE THREAD

**Issue by scbdq** [thijzert/vncreplay#1]
➜  vncreplay git:(master) ✗ ./vncreplay -o player.html /home/kali/Desktop/b3.pcapng

2024/11/09 09:19:58 Unknown encoding type - ignoring whole buffer
panic: runtime error: slice bounds out of range [875407:875395]

goroutine 1 [running]:
github.com/thijzert/vncreplay/rfb.(*RFB).decodeFrameBufferUpdate(0xc0000d3ec0)
        /home/kali/Desktop/vncreplay/rfb/serverEvents.go:78 +0x5bb
github.com/thijzert/vncreplay/rfb.(*RFB).consumeServerEvent(0xc0000d3ec0)
        /home/kali/Desktop/vncreplay/rfb/serverEvents.go:39 +0x355
github.com/thijzert/vncreplay/rfb.(*RFB).Close(0xc0000d3ec0)
        /home/kali/Desktop/vncreplay/rfb/rfb.go:126 +0x351
main.main()
        /home/kali/Desktop/vncreplay/cmd/vncreplay/vncreplay.go:98 +0x89f

**Comment by thijzert** [comment]
Is the pcap you're using available somewhere? The VNC connection probably uses some encoding that this tool doesn't support, but I can at least make sure it doesn't crash as hard.

**Comment by thijzert** [comment]
Commit d286ebea introduced support for some of the encodings that TightVNC uses, I'll assume that's what you were encountering.
